[project]
name = "qcloud-client"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["qcloud", "quantum", "simulation", "api-client"]
dependencies = [
    "httpx>=0.28.1",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.16.0",
]

[project.urls]
Homepage = "https://qcloud.dtu.dk"
Source = "https://github.com/qpit/qcloud-client"
